apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml

namespace: hello-dev

images:
- name: marcelobruckner/hello
  newName: marcelobruckner/hello
  newTag: 9bb495e2f6cbd762910ed2c91820725053bdaf0487c5dc59edf2a5785dda7311
